import {
  User,
  ServiceItem,
  Appointment,
  IntakeSubmission,
  ServiceRequest,
  SecureMessage,
  Conversation,
  ClientDocument,
  CarePlan,
  AuditLog,
  SecurityIncident,
  ProviderProfile,
  NotificationItem,
  CMSContent,
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user_client_1',
    email: 'client@hopecommunity.org',
    firstName: 'Eleanor',
    lastName: 'Vance',
    role: 'client',
    phone: '(803) 555-0142',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    mfaEnabled: false,
    createdAt: '2025-01-15T09:00:00Z',
    lastLoginAt: '2026-09-08T10:15:00Z',
  },
  {
    id: 'user_parent_1',
    email: 'parent@hopecommunity.org',
    firstName: 'Marcus',
    lastName: 'Chen',
    role: 'parent_guardian',
    phone: '(803) 555-0189',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    mfaEnabled: false,
    createdAt: '2025-02-10T14:30:00Z',
    lastLoginAt: '2026-09-07T16:20:00Z',
  },
  {
    id: 'user_provider_1',
    email: 'provider@hopecommunity.org',
    firstName: 'Dr. Sarah',
    lastName: 'Jenkins',
    role: 'provider',
    phone: '(803) 701-9332 ext 102',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    mfaEnabled: true,
    createdAt: '2024-03-01T08:00:00Z',
    lastLoginAt: '2026-09-08T08:45:00Z',
  },
  {
    id: 'user_intake_1',
    email: 'intake@hopecommunity.org',
    firstName: 'Maria',
    lastName: 'Santos',
    role: 'intake_coordinator',
    phone: '(803) 701-9332 ext 104',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    mfaEnabled: true,
    createdAt: '2024-06-12T10:00:00Z',
    lastLoginAt: '2026-09-08T09:10:00Z',
  },
  {
    id: 'user_admin_1',
    email: 'admin@hopecommunity.org',
    firstName: 'David',
    lastName: 'Ross',
    role: 'super_admin',
    phone: '(803) 701-9332 ext 101',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    mfaEnabled: true,
    createdAt: '2023-01-01T08:00:00Z',
    lastLoginAt: '2026-09-08T11:00:00Z',
  },
];

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 'svc_therapy',
    category: 'therapy',
    name: 'Clinical Therapy',
    tagline: 'Evidence-based psychotherapeutic support for healing and growth',
    shortDescription: 'Professional clinical therapy tailored to your personal journey, addressing anxiety, depression, trauma, and emotional distress in a warm, confidential setting.',
    fullDescription: 'Hope Community Support provides comprehensive clinical psychotherapy grounded in empathetic, evidence-based practices. We collaborate with clients to unpack unresolved issues, develop resilient coping strategies, and restore a sense of personal equilibrium.',
    whoItHelps: [
      'Individuals dealing with persistent depressive symptoms',
      'Those navigating generalized or social anxiety',
      'People seeking healing from past trauma or grief',
      'Clients desiring deeper self-awareness and emotional stability',
    ],
    commonConcerns: [
      'Chronic stress and burnout',
      'Unresolved grief and bereavement',
      'Anxiety, panic, or intrusive thoughts',
      'Emotional regulation challenges',
    ],
    whatToExpect: [
      'A thorough, collaborative clinical assessment',
      'A tailored plan focused on your individual goals',
      'Scheduled weekly or bi-weekly 50-minute sessions',
      'Safe, confidential, non-judgmental space',
    ],
    availableFormats: ['office', 'in_home', 'telehealth'],
    faqs: [
      {
        question: 'How long does therapy typically last?',
        answer: 'Treatment duration is individualized. Many clients experience meaningful progress within 8 to 16 sessions, while others benefit from ongoing supportive therapy.',
      },
      {
        question: 'Is therapy confidential?',
        answer: 'Yes, strict behavioral-health privacy laws and ethical standards safeguard your records and conversations, with standard legally mandated safety exceptions.',
      },
    ],
    durationMinutes: 50,
  },
  {
    id: 'svc_intervention',
    category: 'intervention',
    name: 'Behavioral Intervention',
    tagline: 'Direct, compassionate guidance during acute behavioral crises',
    shortDescription: 'Structured, respectful intervention strategies designed to assist individuals and families when substance use, behavioral patterns, or severe distress disrupt stability.',
    fullDescription: 'Our behavioral intervention services offer family and individual-centered support to address high-risk behaviors with dignity. We facilitate constructive conversations, dismantle barriers to care, and establish safe roadmaps into formal treatment.',
    whoItHelps: [
      'Families supporting a loved one with substance misuse',
      'Individuals experiencing acute behavioral deterioration',
      'Loved ones seeking structured de-escalation assistance',
    ],
    commonConcerns: [
      'Substance dependence and addictions',
      'Severe behavioral resistance to care',
      'Family breakdown in communication',
      'Co-occurring emotional distress',
    ],
    whatToExpect: [
      'Pre-intervention family and support network consultations',
      'Structured planning and role clarification',
      'A guided, empathetic intervention meeting',
      'Immediate linkage to appropriate treatment levels',
    ],
    availableFormats: ['office', 'in_home'],
    faqs: [
      {
        question: 'Is intervention confrontational?',
        answer: 'No. Our philosophy is rooted in Hands On Personal Empowerment and compassionate respect, not confrontation or guilt.',
      },
    ],
    durationMinutes: 75,
  },
  {
    id: 'svc_counseling',
    category: 'counseling',
    name: 'Professional Counseling',
    tagline: 'Empowering guidance for life transitions, relationships, and wellness',
    shortDescription: 'Focused, solution-oriented counseling addressing interpersonal dynamics, parenting concerns, stress, and important life milestones.',
    fullDescription: 'Counseling at Hope Community Support helps clients gain perspective, clarify values, and build practical skills. Whether navigating career changes, marital distress, or parenting hurdles, we walk beside you.',
    whoItHelps: [
      'Couples seeking reconnection and improved communication',
      'Parents navigating developmental or behavioral milestones',
      'Professionals experiencing career burnout or transition',
    ],
    commonConcerns: [
      'Communication breakdown in relationships',
      'Parenting stress and family dynamics',
      'Work-life imbalance and life transitions',
      'Self-esteem and interpersonal boundaries',
    ],
    whatToExpect: [
      'Focused goal setting in early sessions',
      'Practical communication and boundary-setting frameworks',
      'Constructive feedback and reflection',
    ],
    availableFormats: ['office', 'telehealth'],
    faqs: [
      {
        question: 'Can my partner and I attend together?',
        answer: 'Yes, our couples and relationship counseling is specifically formatted for dual or family participation.',
      },
    ],
    durationMinutes: 50,
  },
  {
    id: 'svc_training',
    category: 'training',
    name: 'Skill Building & Psychoeducation Training',
    tagline: 'Actionable mental health and wellness skill training',
    shortDescription: 'Structured skill-building modules covering emotional regulation, mindfulness, stress reduction, and healthy communication.',
    fullDescription: 'Our psychoeducational training workshops provide individuals, families, and community groups with concrete tools to navigate stressors. Training combines evidence-based behavioral concepts with realistic daily applications.',
    whoItHelps: [
      'Adults desiring structured stress-management tools',
      'Caregivers seeking trauma-informed care approaches',
      'Community groups fostering wellness literacy',
    ],
    commonConcerns: [
      'Chronic tension and inability to unwind',
      'Lack of assertiveness or boundary-setting skills',
      'Emotional reactivity in high-pressure settings',
    ],
    whatToExpect: [
      'Interactive workbooks and practical exercises',
      'Mindfulness and somatic regulation techniques',
      'Personalized action plans for daily routines',
    ],
    availableFormats: ['office', 'telehealth'],
    faqs: [
      {
        question: 'Are trainings held in groups?',
        answer: 'We offer both individual one-on-one training sessions and small group cohorts.',
      },
    ],
    durationMinutes: 60,
  },
  {
    id: 'svc_mentoring',
    category: 'mentoring',
    name: 'Community & Youth Mentoring',
    tagline: 'Reliable, positive guidance to foster confidence and resilience',
    shortDescription: 'One-on-one mentoring pairing clients with trained mentors who provide consistent support, accountability, and positive reinforcement.',
    fullDescription: 'Mentoring at Hope Community Support connects participants of all ages with dedicated, compassionate mentors. We focus on goal attainment, healthy community integration, academic or vocational growth, and positive identity building.',
    whoItHelps: [
      'Adolescents and young adults needing positive guidance',
      'Individuals reintegrating into community life',
      'Clients working on educational or vocational milestones',
    ],
    commonConcerns: [
      'Isolation and lack of positive role models',
      'Academic disengagement or career stagnation',
      'Difficulty building healthy peer connections',
    ],
    whatToExpect: [
      'Regular weekly or bi-weekly check-ins',
      'Community-based activities and goal tracking',
      'Collaborative work with families and support teams',
    ],
    availableFormats: ['office', 'in_home'],
    faqs: [
      {
        question: 'How are mentors screened?',
        answer: 'All mentors undergo thorough background verification, credential reviews, and ongoing clinical supervision.',
      },
    ],
    durationMinutes: 60,
  },
  {
    id: 'svc_telehealth',
    category: 'telehealth',
    name: 'Telehealth Care Sessions',
    tagline: 'Encrypted, confidential virtual care from the comfort of home',
    shortDescription: 'Secure video appointments offering the same dedicated care as in-office visits, accessible across South Carolina without commute barriers.',
    fullDescription: 'Hope Community Support provides private telehealth visits accessible via any computer, tablet, or smartphone. Our HIPAA-compliant virtual consultation rooms make high-quality therapy and counseling convenient and accessible.',
    whoItHelps: [
      'Clients with transportation limitations or busy schedules',
      'Individuals residing throughout South Carolina',
      'Anyone prioritizing the comfort of home-based virtual sessions',
    ],
    commonConcerns: [
      'Geographic distance from downtown Rock Hill',
      'Mobility challenges or child-care constraints',
      'Tight work schedules requiring flexible access',
    ],
    whatToExpect: [
      'One-click secure video link delivered to your portal and email',
      'Encrypted end-to-end video and audio connection',
      'The same dedicated 50-minute clinical care',
    ],
    availableFormats: ['telehealth'],
    faqs: [
      {
        question: 'What technology do I need?',
        answer: 'Any device with a web browser, webcam, microphone, and a reliable internet connection.',
      },
    ],
    durationMinutes: 50,
  },
  {
    id: 'svc_in_home',
    category: 'in_home',
    name: 'In-Home Supportive Services',
    tagline: 'Meeting you where you are in your natural environment',
    shortDescription: 'Compassionate behavioral health support provided directly in the client’s home, bridging barriers to clinic attendance.',
    fullDescription: 'For clients facing medical, transportation, or emotional hurdles to office visits, Hope Community Support brings care directly to your residence. Our staff creates a comfortable, respectful dynamic in your home space.',
    whoItHelps: [
      'Families with mobility constraints or limited transport',
      'Clients where natural home observation aids intervention',
      'Individuals feeling safer receiving care in their residence',
    ],
    commonConcerns: [
      'Transportation barriers to Rock Hill office',
      'Family system challenges requiring in-situ coaching',
    ],
    whatToExpect: [
      'Scheduled provider home visits with verified credentials',
      'Safety and privacy protocols established on arrival',
      'Compassionate, respectful in-person interaction',
    ],
    availableFormats: ['in_home'],
    faqs: [
      {
        question: 'What areas do in-home services cover?',
        answer: 'We provide in-home services throughout the greater Rock Hill, York County, and surrounding South Carolina communities.',
      },
    ],
    durationMinutes: 60,
  },
];

export const INITIAL_PROVIDERS: ProviderProfile[] = [
  {
    id: 'prov_1',
    userId: 'user_provider_1',
    name: 'Dr. Sarah Jenkins',
    credentials: 'PhD, LPC, NCC',
    roleTitle: 'Clinical Director & Licensed Professional Counselor',
    areasOfFocus: ['Grief & Loss', 'Depression & Mood Disorders', 'Trauma Recovery', 'Anxiety'],
    specialties: ['Cognitive Behavioral Therapy (CBT)', 'EMDR-Informed Care', 'Somatic Regulation'],
    deliveryMethods: ['office', 'telehealth'],
    languages: ['English'],
    shortBio: 'Over 16 years of dedicated practice empowering individuals and families through empathetic, evidence-based psychotherapeutic care. Dedicated to the founding vision of Hope Community Support.',
    isAcceptingNewClients: true,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    verificationBadge: 'Verified SC State License #LPC-8912',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'],
  },
  {
    id: 'prov_2',
    userId: 'prov_placeholder_2',
    name: 'Marcus Sterling',
    credentials: 'MSW, LISW-CP',
    roleTitle: 'Senior Clinical Social Worker & Family Specialist',
    areasOfFocus: ['Couples & Family Dynamics', 'Addictions & Recovery', 'Parenting Support'],
    specialties: ['Systemic Family Therapy', 'Motivational Interviewing', 'Relapse Prevention'],
    deliveryMethods: ['office', 'in_home', 'telehealth'],
    languages: ['English', 'Spanish'],
    shortBio: 'Specializing in relational restoration and family systems support, bringing warmth and structured tools to complex family dynamics.',
    isAcceptingNewClients: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    verificationBadge: 'Verified SC State License #LISW-4418',
    availableDays: ['Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  },
  {
    id: 'prov_3',
    userId: 'prov_placeholder_3',
    name: 'Elena Rostova',
    credentials: 'MA, LAC, CPSS',
    roleTitle: 'Behavioral Interventionist & Mentor Lead',
    areasOfFocus: ['Career Transitions', 'Stress Management', 'Youth Mentoring', 'Life Skills'],
    specialties: ['Solution-Focused Brief Therapy', 'Peer Empowerment', 'Habit Reformation'],
    deliveryMethods: ['office', 'in_home'],
    languages: ['English'],
    shortBio: 'Passionate advocate for personal autonomy and hands-on skill development, helping participants build lifelong emotional resilience.',
    isAcceptingNewClients: true,
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&auto=format&fit=crop&q=80',
    verificationBadge: 'Verified SC State Credential #LAC-7821',
    availableDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt_101',
    clientId: 'user_client_1',
    clientName: 'Eleanor Vance',
    clientEmail: 'client@hopecommunity.org',
    clientPhone: '(803) 555-0142',
    providerId: 'user_provider_1',
    providerName: 'Dr. Sarah Jenkins',
    serviceId: 'svc_therapy',
    serviceName: 'Clinical Therapy',
    deliveryMethod: 'office',
    participantType: 'individual',
    date: '2026-09-15',
    timeSlot: '10:00 AM',
    durationMinutes: 50,
    status: 'confirmed',
    notes: 'Follow-up on stress management and boundary reinforcement.',
    internalStaffNotes: 'Client responded well to prior CBT journal exercise. Review coping worksheet.',
    telehealthLink: '',
    createdAt: '2026-09-01T11:00:00Z',
    updatedAt: '2026-09-02T09:30:00Z',
  },
  {
    id: 'apt_102',
    clientId: 'user_client_1',
    clientName: 'Eleanor Vance',
    clientEmail: 'client@hopecommunity.org',
    clientPhone: '(803) 555-0142',
    providerId: 'user_provider_1',
    providerName: 'Dr. Sarah Jenkins',
    serviceId: 'svc_telehealth',
    serviceName: 'Telehealth Care Sessions',
    deliveryMethod: 'telehealth',
    participantType: 'individual',
    date: '2026-09-22',
    timeSlot: '02:00 PM',
    durationMinutes: 50,
    status: 'requested',
    notes: 'Mid-month check-in regarding career transition anxiety.',
    telehealthLink: 'https://meet.hopecommunitysupport.com/room/hcs-vance-7821',
    createdAt: '2026-09-06T15:20:00Z',
    updatedAt: '2026-09-06T15:20:00Z',
  },
  {
    id: 'apt_103',
    clientId: 'user_client_1',
    clientName: 'Eleanor Vance',
    clientEmail: 'client@hopecommunity.org',
    clientPhone: '(803) 555-0142',
    providerId: 'user_provider_1',
    providerName: 'Dr. Sarah Jenkins',
    serviceId: 'svc_therapy',
    serviceName: 'Clinical Therapy',
    deliveryMethod: 'office',
    participantType: 'individual',
    date: '2026-08-25',
    timeSlot: '10:00 AM',
    durationMinutes: 50,
    status: 'completed',
    notes: 'Initial clinical intake and care plan establishment.',
    internalStaffNotes: 'Intake completed thoroughly. Client motivated.',
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-25T11:00:00Z',
  },
  {
    id: 'apt_104',
    clientId: 'user_parent_1',
    clientName: 'Marcus Chen',
    clientEmail: 'parent@hopecommunity.org',
    clientPhone: '(803) 555-0189',
    providerId: 'prov_2',
    providerName: 'Marcus Sterling',
    serviceId: 'svc_counseling',
    serviceName: 'Professional Counseling',
    deliveryMethod: 'office',
    participantType: 'family',
    date: '2026-09-16',
    timeSlot: '04:00 PM',
    durationMinutes: 50,
    status: 'confirmed',
    notes: 'Family communication session.',
    createdAt: '2026-09-04T12:00:00Z',
    updatedAt: '2026-09-05T09:00:00Z',
  },
];

export const INITIAL_INTAKES: IntakeSubmission[] = [
  {
    id: 'intake_201',
    clientId: 'user_client_1',
    clientName: 'Eleanor Vance',
    dateOfBirth: '1992-05-14',
    phone: '(803) 555-0142',
    address: '412 Calhoun St, Rock Hill, SC 29730',
    emergencyContact: {
      name: 'Claire Vance',
      relationship: 'Sister',
      phone: '(803) 555-0199',
    },
    preferredLanguage: 'English',
    serviceRequested: 'Clinical Therapy',
    preferredDelivery: 'office',
    insuranceType: 'private',
    insuranceProvider: 'BlueCross BlueShield of SC',
    policyNumber: 'BCSC-8892104',
    primaryConcerns: ['Anxiety', 'Stress Management', 'Career Transitions'],
    symptomSeverity: 'moderate',
    currentMedications: 'None reported',
    priorMentalHealthCare: true,
    priorCareDetails: 'Attended brief counseling in college for academic stress.',
    consentTreatmentSigned: true,
    consentTelehealthSigned: true,
    hipaaAcknowledged: true,
    signatureDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="60"><text x="10" y="40" font-family="cursive" font-size="24" fill="%23173F3A">Eleanor Vance</text></svg>',
    signatureDate: '2026-08-20T14:35:00Z',
    status: 'approved',
    staffReviewerNotes: 'Intake fully verified by Maria Santos, MSW. Assigned to Dr. Sarah Jenkins.',
    submittedAt: '2026-08-20T14:35:00Z',
    reviewedAt: '2026-08-21T09:00:00Z',
  },
  {
    id: 'intake_202',
    clientId: 'user_parent_1',
    clientName: 'Marcus Chen',
    dateOfBirth: '1984-11-29',
    phone: '(803) 555-0189',
    address: '1280 India Hook Rd, Rock Hill, SC 29732',
    emergencyContact: {
      name: 'Jennifer Chen',
      relationship: 'Spouse',
      phone: '(803) 555-0190',
    },
    preferredLanguage: 'English',
    serviceRequested: 'Family Counseling',
    preferredDelivery: 'office',
    insuranceType: 'self_pay',
    primaryConcerns: ['Parenting', 'Relationship concerns'],
    symptomSeverity: 'mild',
    priorMentalHealthCare: false,
    consentTreatmentSigned: true,
    consentTelehealthSigned: true,
    hipaaAcknowledged: true,
    signatureDate: '2026-09-02T10:15:00Z',
    status: 'pending_review',
    submittedAt: '2026-09-02T10:15:00Z',
  },
];

export const INITIAL_SERVICE_REQUESTS: ServiceRequest[] = [
  {
    id: 'req_301',
    clientId: 'user_client_1',
    clientName: 'Eleanor Vance',
    serviceType: 'Therapy & Stress Management',
    preferredDelivery: 'office',
    urgency: 'routine',
    details: 'Looking to explore additional stress management workshops or group sessions in the evenings.',
    preferredTimes: ['Tuesday Evenings', 'Thursday Evenings'],
    status: 'under_review',
    assignedStaffId: 'user_intake_1',
    assignedStaffName: 'Maria Santos',
    responseNotes: 'Evaluating upcoming mindfulness and training cohort schedule.',
    createdAt: '2026-09-05T13:00:00Z',
    updatedAt: '2026-09-06T10:30:00Z',
  },
  {
    id: 'req_302',
    clientId: 'user_parent_1',
    clientName: 'Marcus Chen',
    serviceType: 'Parenting Support Session',
    preferredDelivery: 'office',
    urgency: 'routine',
    details: 'Requesting guidance on positive communication techniques for pre-teens.',
    preferredTimes: ['Weekday afternoons'],
    status: 'assigned',
    assignedStaffId: 'user_provider_1',
    assignedStaffName: 'Dr. Sarah Jenkins',
    createdAt: '2026-09-03T16:00:00Z',
    updatedAt: '2026-09-04T11:00:00Z',
  },
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_1',
    clientId: 'user_client_1',
    clientName: 'Eleanor Vance',
    staffId: 'user_provider_1',
    staffName: 'Dr. Sarah Jenkins',
    lastMessage: 'I have reviewed your coping worksheet. We will discuss it during Tuesday’s session.',
    lastMessageAt: '2026-09-07T14:22:00Z',
    unreadCountClient: 1,
    unreadCountStaff: 0,
  },
  {
    id: 'conv_2',
    clientId: 'user_parent_1',
    clientName: 'Marcus Chen',
    staffId: 'user_intake_1',
    staffName: 'Maria Santos',
    lastMessage: 'Your intake paperwork has been received. Thank you!',
    lastMessageAt: '2026-09-02T11:00:00Z',
    unreadCountClient: 0,
    unreadCountStaff: 0,
  },
];

export const INITIAL_MESSAGES: SecureMessage[] = [
  {
    id: 'msg_1',
    conversationId: 'conv_1',
    senderId: 'user_client_1',
    senderName: 'Eleanor Vance',
    senderRole: 'client',
    recipientId: 'user_provider_1',
    subject: 'Question on weekly reflection sheet',
    content: 'Good morning Dr. Jenkins, I completed the journal entries we spoke about. Should I bring the physical notes to our appointment or upload them to the portal?',
    isRead: true,
    createdAt: '2026-09-07T11:15:00Z',
  },
  {
    id: 'msg_2',
    conversationId: 'conv_1',
    senderId: 'user_provider_1',
    senderName: 'Dr. Sarah Jenkins',
    senderRole: 'provider',
    recipientId: 'user_client_1',
    subject: 'Re: Question on weekly reflection sheet',
    content: 'Hello Eleanor, bringing the physical notes is great, or feel free to upload a quick photo in your portal documents. I have reviewed your coping worksheet and look forward to discussing it during Tuesday’s session.',
    isRead: false,
    createdAt: '2026-09-07T14:22:00Z',
  },
];

export const INITIAL_DOCUMENTS: ClientDocument[] = [
  {
    id: 'doc_1',
    clientId: 'user_client_1',
    uploaderId: 'user_client_1',
    uploaderName: 'Eleanor Vance',
    uploaderRole: 'client',
    title: 'Signed Consent for Treatment & Telehealth',
    fileName: 'Consent_Treatment_Vance_signed.pdf',
    fileSize: '245 KB',
    fileType: 'application/pdf',
    category: 'intake_consent',
    isSharedWithClient: true,
    uploadedAt: '2026-08-20T14:35:00Z',
  },
  {
    id: 'doc_2',
    clientId: 'user_client_1',
    uploaderId: 'user_client_1',
    uploaderName: 'Eleanor Vance',
    uploaderRole: 'client',
    title: 'Insurance Card (Front & Back)',
    fileName: 'BCBS_Insurance_Card_2026.pdf',
    fileSize: '1.2 MB',
    fileType: 'application/pdf',
    category: 'insurance_id',
    isSharedWithClient: true,
    uploadedAt: '2026-08-20T14:38:00Z',
  },
  {
    id: 'doc_3',
    clientId: 'user_client_1',
    uploaderId: 'user_provider_1',
    uploaderName: 'Dr. Sarah Jenkins',
    uploaderRole: 'provider',
    title: 'Individualized Service Plan Summary',
    fileName: 'HCS_Service_Plan_Vance_Rev1.pdf',
    fileSize: '180 KB',
    fileType: 'application/pdf',
    category: 'care_plan',
    isSharedWithClient: true,
    uploadedAt: '2026-08-26T16:00:00Z',
  },
];

export const INITIAL_CARE_PLANS: CarePlan[] = [
  {
    id: 'plan_1',
    clientId: 'user_client_1',
    clientName: 'Eleanor Vance',
    providerId: 'user_provider_1',
    providerName: 'Dr. Sarah Jenkins',
    diagnosisOrFocus: 'Adjustment with Anxiety; Career Transition Stress',
    primaryGoals: [
      'Identify and implement 3 somatic grounding techniques during acute stress triggers.',
      'Establish healthy professional boundary frameworks to reduce workplace burnout.',
      'Increase participation in positive community and social activities.',
    ],
    interventionStrategies: [
      'Cognitive restructuring exercises to challenge catastrophic thinking.',
      'Bi-weekly progress monitoring with self-regulation logs.',
      'Psychoeducation on sleep hygiene and nervous system regulation.',
    ],
    reviewDate: '2026-11-25',
    status: 'active',
    createdAt: '2026-08-26T15:30:00Z',
    updatedAt: '2026-08-26T15:30:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit_1',
    timestamp: '2026-09-08T11:00:00Z',
    userId: 'user_admin_1',
    userName: 'David Ross',
    userRole: 'super_admin',
    action: 'SYSTEM_SETTINGS_UPDATE',
    entity: 'system_settings',
    entityId: 'global_cms',
    ipAddress: '198.51.100.24',
    details: 'Updated crisis hotline emergency notice banner wording.',
    severity: 'info',
  },
  {
    id: 'audit_2',
    timestamp: '2026-09-08T09:15:00Z',
    userId: 'user_intake_1',
    userName: 'Maria Santos',
    userRole: 'intake_coordinator',
    action: 'INTAKE_REVIEW_ACCESSED',
    entity: 'intake_submissions',
    entityId: 'intake_202',
    ipAddress: '198.51.100.12',
    details: 'Accessed pending intake submission for Marcus Chen.',
    severity: 'info',
  },
  {
    id: 'audit_3',
    timestamp: '2026-09-07T16:30:00Z',
    userId: 'user_provider_1',
    userName: 'Dr. Sarah Jenkins',
    userRole: 'provider',
    action: 'CARE_PLAN_VIEWED',
    entity: 'care_plans',
    entityId: 'plan_1',
    ipAddress: '198.51.100.8',
    details: 'Viewed active care plan for client Eleanor Vance.',
    severity: 'info',
  },
  {
    id: 'audit_4',
    timestamp: '2026-09-06T14:10:00Z',
    userId: 'user_admin_1',
    userName: 'David Ross',
    userRole: 'super_admin',
    action: 'SECURITY_AUDIT_REVIEW',
    entity: 'audit_logs',
    entityId: 'export_q3',
    ipAddress: '198.51.100.24',
    details: 'Generated compliance access log verification report.',
    severity: 'info',
  },
];

export const INITIAL_SECURITY_INCIDENTS: SecurityIncident[] = [
  {
    id: 'inc_1',
    reportedAt: '2026-09-01T08:30:00Z',
    reporterId: 'user_admin_1',
    reporterName: 'David Ross',
    type: 'unauthorized_access_attempt',
    severity: 'low',
    description: 'Blocked 3 consecutive failed login attempts from unrecognized IP range. Account lock safely enforced.',
    status: 'mitigated',
    resolutionNotes: 'IP address rate-limited for 60 minutes. Legitimate client successfully completed password reset.',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    userId: 'user_client_1',
    title: 'Upcoming Appointment Confirmed',
    message: 'Your in-office appointment with Dr. Sarah Jenkins is scheduled for Sep 15, 2026 at 10:00 AM.',
    type: 'appointment',
    isRead: false,
    createdAt: '2026-09-02T09:30:00Z',
    actionUrl: '#appointments',
  },
  {
    id: 'notif_2',
    userId: 'user_client_1',
    title: 'New Secure Message',
    message: 'Dr. Sarah Jenkins sent a reply in your secure portal messages.',
    type: 'message',
    isRead: false,
    createdAt: '2026-09-07T14:22:00Z',
    actionUrl: '#messages',
  },
  {
    id: 'notif_3',
    userId: 'user_client_1',
    title: 'Intake Paperwork Approved',
    message: 'Your intake paperwork has been reviewed and verified by our clinical coordination team.',
    type: 'intake',
    isRead: true,
    createdAt: '2026-08-21T09:00:00Z',
  },
];

export const INITIAL_CMS: CMSContent = {
  announcementNotice: 'Hope Community Support continues to accept new clients for office, in-home, and telehealth services.',
  heroHeadline: 'Compassionate Support for Every Stage of Life',
  heroSubtitle: 'Personalized therapy, intervention, counseling, training, and mentoring for individuals, couples, families, and groups. Serving South Carolina with Hands On Personal Empowerment since 2008.',
  emergencyCrisisNotice: 'This platform is not an emergency service and is not monitored continuously. If you or someone else is in immediate danger, call 911. For mental-health crisis support in the United States, call or text 988.',
  officeHours: 'Monday – Thursday: 8:30 AM – 6:00 PM | Friday: 9:00 AM – 4:00 PM | Weekend appointments available by request',
  phoneNumber: '803-701-9332',
  faxNumber: '980-217-8340',
  emailAddress: 'hopecommunitysc@gmail.com',
  officeAddress: '331 E Main Street Downtown, Suite 200, Rock Hill, SC 29730',
  lastUpdated: '2026-09-08',
};
